### ISSUE TITLE
I follow the steps, why do I get an error?

### ISSUE THREAD

**Issue by WangYu0611** [city-super/Octree-GS#17]
(octree-gs) wy@wy-MS-7D32:~/Octree-GS$ bash train_bungeenerf.sh
0
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
/home/wy/miniconda3/envs/octree-gs/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
/home/wy/miniconda3/envs/octree-gs/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/wy/miniconda3/envs/octree-gs/lib/python3.7/site-packages/lpips/weights/v0.1/vgg.pth
not found tf board
2024-04-30 17:24:53,533 - INFO: args: Namespace(add_color_dist=False, add_cov_dist=False, add_level=False, add_opacity_dist=False, appearance_dim=0, appearance_lr_delay_mult=0.01, appearance_lr_final=0.0005, appearance_lr_init=0.05, appearance_lr_max_steps=40000, base_layer=10, checkpoint_iterations=[], coarse_factor=1.5, coarse_iter=5000, compute_cov3D_python=False, data_device='cuda', debug=False, debug_from=-1, densify_grad_threshold=0.0002, detect_anomaly=False, dist2level='round', dist_ratio=0.99, ds=1, eval=True, extend=1.1, extra_ratio=0.25, extra_up=0.01, feat_dim=32, feature_lr=0.0075, fork=2, gpu='-1', images='images', init_level=-1, ip='127.0.0.1', iterations=40000, lambda_dssim=0.2, levels=-1, min_opacity=0.005, mlp_color_lr_delay_mult=0.01, mlp_color_lr_final=5e-05, mlp_color_lr_init=0.008, mlp_color_lr_max_steps=40000, mlp_cov_lr_delay_mult=0.01, mlp_cov_lr_final=0.004, mlp_cov_lr_init=0.004, mlp_cov_lr_max_steps=40000, mlp_featurebank_lr_delay_mult=0.01, mlp_featurebank_lr_final=1e-05, mlp_featurebank_lr_init=0.01, mlp_featurebank_lr_max_steps=40000, mlp_opacity_lr_delay_mult=0.01, mlp_opacity_lr_final=2e-05, mlp_opacity_lr_init=0.002, mlp_opacity_lr_max_steps=40000, model_path='outputs/bungeenerf/hollywood/baseline/2024-04-30_17:24:51', n_offsets=10, offset_lr_delay_mult=0.01, offset_lr_final=0.0001, offset_lr_init=0.01, offset_lr_max_steps=40000, opacity_lr=0.02, percent_dense=0.01, port=29360, position_lr_delay_mult=0.01, position_lr_final=0.0, position_lr_init=0.0, position_lr_max_steps=40000, progressive=True, quiet=False, random_background=False, ratio=1, resolution=-1, resolution_scales=[1.0], rotation_lr=0.002, save_iterations=[-1], scaling_lr=0.007, source_path='data/bungeenerf/hollywood', start_checkpoint=None, start_stat=500, success_threshold=0.8, test_iterations=[-1], undistorted=False, update_anchor=True, update_from=1500, update_interval=100, update_ratio=0.2, update_until=20000, use_feat_bank=False, use_wandb=False, visible_threshold=0.0, warmup=False, white_background=False)
[10000, 20000, 30000, 40000]
[10000, 20000, 30000, 40000]
Backup Finished!
2024-04-30 17:25:01,392 - INFO: Optimizing outputs/bungeenerf/hollywood/baseline/2024-04-30_17:24:51
Output folder: outputs/bungeenerf/hollywood/baseline/2024-04-30_17:24:51 [30/04 17:25:01]
Tensorboard not available: not logging progress [30/04 17:25:01]
Traceback (most recent call last):
  File "train.py", line 560, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), dataset,  args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, wandb, logger)
  File "train.py", line 89, in training
    scene = Scene(dataset, gaussians, ply_path=ply_path, shuffle=False, logger=logger, resolution_scales=dataset.resolution_scales)
  File "/home/wy/Octree-GS/scene/__init__.py", line 51, in __init__
    scene_info = sceneLoadTypeCallbacks["City"](args.source_path, args.random_background, args.white_background, args.eval, args.ds, undistorted=args.undistorted)
  File "/home/wy/Octree-GS/scene/dataset_readers.py", line 381, in readCityInfo
    json_path = glob.glob(os.path.join(path, f"*.json"))[0].split('/')[-1]
IndexError: list index out of range

**Comment by tongji-rkr** [comment]
Did you check `data/bungeenerf/hollywood`? I guess it is empty.

**Comment by WangYu0611** [comment]
> Did you check `data/bungeenerf/hollywood`? I guess it is empty.

sorry, i check it , path is  wrong
