### ISSUE TITLE
Three Python libraries are missing in the `environment.yaml` file

### ISSUE THREAD

**Issue by Deng-King** [city-super/Octree-GS#37]
Hi there,

Thanks for your exceptional work on the large scale reconstruction project. It's truly impressive!

While attempting to run the provided code, I've noticed that the `environment.yaml` file seems to be missing a few libraries. Specifically, these are `jaxtyping`, `colorama`, and `opencv-python`.

Here's the error message I encountered when I tried to execute `single_train.sh`:

```bash
(octree-gs) deng@deng-precision-7920-tower-with4090:/media/deng/Data/Octree-GS$ bash single_train.sh
0
Traceback (most recent call last):
  File "/media/deng/Data/Octree-GS/train.py", line 36, in <module>
    from gaussian_renderer import prefilter_voxel, render, network_gui
  File "/media/deng/Data/Octree-GS/gaussian_renderer/__init__.py", line 16, in <module>
    from scene.gaussian_model import GaussianModel
  File "/media/deng/Data/Octree-GS/scene/__init__.py", line 17, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks, storePly
  File "/media/deng/Data/Octree-GS/scene/dataset_readers.py", line 18, in <module>
    from colorama import Fore, init, Style
ModuleNotFoundError: No module named 'colorama'
(octree-gs) deng@deng-precision-7920-tower-with4090:/media/deng/Data/Octree-GS$ pip install colorama
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: colorama
Successfully installed colorama-0.4.6
(octree-gs) deng@deng-precision-7920-tower-with4090:/media/deng/Data/Octree-GS$ bash single_train.sh
0
Traceback (most recent call last):
  File "/media/deng/Data/Octree-GS/train.py", line 36, in <module>
    from gaussian_renderer import prefilter_voxel, render, network_gui
  File "/media/deng/Data/Octree-GS/gaussian_renderer/__init__.py", line 16, in <module>
    from scene.gaussian_model import GaussianModel
  File "/media/deng/Data/Octree-GS/scene/__init__.py", line 17, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks, storePly
  File "/media/deng/Data/Octree-GS/scene/dataset_readers.py", line 30, in <module>
    from scene.gaussian_model import BasicPointCloud
  File "/media/deng/Data/Octree-GS/scene/gaussian_model.py", line 26, in <module>
    from scene.embedding import Embedding
  File "/media/deng/Data/Octree-GS/scene/embedding.py", line 4, in <module>
    from jaxtyping import Shaped
ModuleNotFoundError: No module named 'jaxtyping'
(octree-gs) deng@deng-precision-7920-tower-with4090:/media/deng/Data/Octree-GS$ pip install jaxtyping
Collecting jaxtyping

  Downloading jaxtyping-0.2.31-py3-none-any.whl.metadata (6.4 kB)
Collecting typeguard==2.13.3 (from jaxtyping)
  Downloading typeguard-2.13.3-py3-none-any.whl.metadata (3.6 kB)
Downloading jaxtyping-0.2.31-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 kB 275.2 kB/s eta 0:00:00
Downloading typeguard-2.13.3-py3-none-any.whl (17 kB)
Installing collected packages: typeguard, jaxtyping
Successfully installed jaxtyping-0.2.31 typeguard-2.13.3
(octree-gs) deng@deng-precision-7920-tower-with4090:/media/deng/Data/Octree-GS$ 
(octree-gs) deng@deng-precision-7920-tower-with4090:/media/deng/Data/Octree-GS$ bash single_train.sh
0
Traceback (most recent call last):
  File "/media/deng/Data/Octree-GS/train.py", line 36, in <module>
    from gaussian_renderer import prefilter_voxel, render, network_gui
  File "/media/deng/Data/Octree-GS/gaussian_renderer/__init__.py", line 16, in <module>
    from scene.gaussian_model import GaussianModel
  File "/media/deng/Data/Octree-GS/scene/__init__.py", line 17, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks, storePly
  File "/media/deng/Data/Octree-GS/scene/dataset_readers.py", line 31, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
(octree-gs) deng@deng-precision-7920-tower-with4090:/media/deng/Data/Octree-GS$ pip install opencv-python
Collecting opencv-python
  Downloading opencv_python-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Requirement already satisfied: numpy>=1.21.2 in /home/deng/miniconda3/envs/octree-gs/lib/python3.10/site-packages (from opencv-python) (1.26.3)
Downloading opencv_python-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (62.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.5/62.5 MB 2.6 MB/s eta 0:00:00
Installing collected packages: opencv-python
Successfully installed opencv-python-4.10.0.84
(octree-gs) deng@deng-precision-7920-tower-with4090:/media/deng/Data/Octree-GS$ bash single_train.sh
0
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]

...

```

To enhance the user experience and ease of setup, I suggest including the aforementioned libraries in the `environment.yaml` file. This would ensure a smoother setup process for future users.

Thank you for considering this suggestion. Your work is greatly appreciated!

**Comment by tongji-rkr** [comment]
Thanks for your suggestion, I have modified `environment.yaml`.
